version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16.3
    restart: always
    env_file:
      - ./tgBot/tgBot/.env
    volumes:
      - ./postgres:/var/lib/postgressql/data/
    ports:
      - 5432:5432


  pgadmin4:
    image: elestio/pgadmin
    restart: always
    env_file:
      - ./tgBot/tgBot/.env        
    environment:
          # Дополнительные настройки
      PGADMIN_CONFIG_ENHANCED_SECURITY: "False"
      PGADMIN_LISTEN_PORT: 8080
    ports:
    - 8080:8080
    volumes:
    - ./servers.json:/pgadmin4/servers.json


  web:
    container_name: web
    build: .
    command: >
      /bin/sh -c "sleep 5 && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000 & 
      python manage.py bot_asinc"

    ports:
      - "8000:8000"
    depends_on:
      - db

