# Generated by Django 5.0 on 2024-01-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
