# Generated by Django 5.0 on 2024-01-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0002_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
