# Generated by Django 5.0 on 2024-01-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0003_video_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='voiceover_studio',
        ),
    ]
