# Generated by Django 5.0 on 2024-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0007_alter_series_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(blank=True, max_length=32),
        ),
    ]
