# Generated by Django 5.0 on 2024-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0009_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(blank=True, default='', max_length=32, null=True),
        ),
    ]
