# Generated by Django 5.0 on 2024-02-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0010_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='advertising_maximum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='id_advertising',
            field=models.BooleanField(default=False),
        ),
    ]
