# Generated by Django 5.0 on 2024-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0012_users_is_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.TextField(blank=True, default='', max_length=64, null=True),
        ),
    ]
