# Generated by Django 5.0 on 2024-02-21 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0017_channel_name_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
