# Generated by Django 5.0 on 2024-02-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0018_users_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='advertising_maximum',
        ),
    ]
