# Generated by Django 5.0 on 2024-02-21 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0020_alter_channel_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_super_channel',
            field=models.BooleanField(default=False, verbose_name='Является ли канал супер важным для постинга сериалов'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Изображение для сериала(по ID телеграмма)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_subscription',
            field=models.BooleanField(default=False, verbose_name='Подписался ли пользователь на каналы-спосноры'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Является ли пользователь админом'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.IntegerField(verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.IntegerField(verbose_name='Номер сезона'),
        ),
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot1.series', verbose_name='Какому сериалу принадлежит'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=64, verbose_name='ID видое файла из тг'),
        ),
    ]
