# Generated by Django 5.0 on 2024-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0021_alter_channel_is_super_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=64, verbose_name='ID видео файла из тг'),
        ),
    ]
