# Generated by Django 5.0 on 2024-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0022_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
