# Generated by Django 5.0 on 2024-02-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0024_remove_series_genres_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
