# Generated by Django 5.0 on 2024-03-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0025_serviceusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceusage',
            options={'verbose_name': 'Статистика активности', 'verbose_name_plural': 'Статистика активности'},
        ),
    ]
