# Generated by Django 5.0 on 2024-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0026_alter_serviceusage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers_added',
            field=models.IntegerField(default=0, verbose_name='Пришло подписчиков'),
        ),
    ]
