# Generated by Django 5.0 on 2024-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0030_alter_users_ref_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='ban_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Забанен во время: '),
        ),
        migrations.AddField(
            model_name='users',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='Забанен'),
        ),
        migrations.AddField(
            model_name='users',
            name='messages_per_second',
            field=models.IntegerField(default=0, verbose_name='Количество сообщений в секунду'),
        ),
    ]
