# Generated by Django 5.0 on 2024-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0032_alter_series_poster_alter_users_messages_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_release',
            field=models.BooleanField(default=False, verbose_name='Аниме в продакшене и доступно пользователем'),
        ),
    ]
