# Generated by Django 5.0 on 2024-04-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0035_users_series_seriesusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, to='bot1.series', verbose_name='Просмотренное за месяц'),
        ),
    ]
