# Generated by Django 5.0.6 on 2024-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0037_alter_seriesusage_date_alter_users_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscribers_added',
            field=models.PositiveIntegerField(default=0, verbose_name='Пришло подписчиков'),
        ),
        migrations.AlterField(
            model_name='seriesusage',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceusage',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statisticref',
            name='user_sdded',
            field=models.PositiveIntegerField(default=0, verbose_name='Пришло юзеров'),
        ),
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.PositiveIntegerField(verbose_name='Номер сезона'),
        ),
    ]
